name: countryman_radar
description: A Countryman Radar Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  get: ^4.1.4
  get_storage: ^2.0.2
  http: ^0.13.1
  cloud_firestore: ^1.0.4
  google_fonts: ^2.0.0
  package_info_plus: ^1.0.0
  pin_code_text_field: ^1.8.0
  intl_phone_number_input: ^0.7.0+1
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  lottie: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.7+1

flutter_native_splash:

  color: "#ffffff"
  image: assets/splash/splash.png
  color_dark: "#ffffff"
  image_dark: assets/splash/splash.png
  android: true
  ios: true
  web: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  web_image_mode: contain
  fullscreen: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
